// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "todo.proto" (package "todo", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TodoService } from "./todo";
import type { DeleteTodoResponse } from "./todo";
import type { DeleteTodoRequest } from "./todo";
import type { GetTodosResponse } from "./todo";
import type { GetTodosRequest } from "./todo";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AddTodoItemResponse } from "./todo";
import type { TodoItem } from "./todo";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service todo.TodoService
 */
export interface ITodoServiceClient {
    /**
     * @generated from protobuf rpc: AddTodo
     */
    addTodo(input: TodoItem, options?: RpcOptions): UnaryCall<TodoItem, AddTodoItemResponse>;
    /**
     * @generated from protobuf rpc: GetTodos
     */
    getTodos(input: GetTodosRequest, options?: RpcOptions): UnaryCall<GetTodosRequest, GetTodosResponse>;
    /**
     * @generated from protobuf rpc: DeleteTodo
     */
    deleteTodo(input: DeleteTodoRequest, options?: RpcOptions): UnaryCall<DeleteTodoRequest, DeleteTodoResponse>;
}
/**
 * @generated from protobuf service todo.TodoService
 */
export class TodoServiceClient implements ITodoServiceClient, ServiceInfo {
    typeName = TodoService.typeName;
    methods = TodoService.methods;
    options = TodoService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddTodo
     */
    addTodo(input: TodoItem, options?: RpcOptions): UnaryCall<TodoItem, AddTodoItemResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TodoItem, AddTodoItemResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTodos
     */
    getTodos(input: GetTodosRequest, options?: RpcOptions): UnaryCall<GetTodosRequest, GetTodosResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTodosRequest, GetTodosResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTodo
     */
    deleteTodo(input: DeleteTodoRequest, options?: RpcOptions): UnaryCall<DeleteTodoRequest, DeleteTodoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteTodoRequest, DeleteTodoResponse>("unary", this._transport, method, opt, input);
    }
}
