// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "todo.proto" (package "todo", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message todo.TodoItem
 */
export interface TodoItem {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: todo.TodoStatus status = 3
     */
    status: TodoStatus;
    /**
     * @generated from protobuf field: optional string created_at = 4
     */
    createdAt?: string;
    /**
     * @generated from protobuf field: optional string updated_at = 5
     */
    updatedAt?: string;
    /**
     * @generated from protobuf field: string user_id = 6
     */
    userId: string;
}
/**
 * @generated from protobuf message todo.AddTodoItemResponse
 */
export interface AddTodoItemResponse {
    /**
     * @generated from protobuf field: todo.TodoItem item = 1
     */
    item?: TodoItem;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: bool success = 3
     */
    success: boolean;
    /**
     * @generated from protobuf field: int32 code = 4
     */
    code: number;
}
/**
 * @generated from protobuf message todo.GetTodosResponse
 */
export interface GetTodosResponse {
    /**
     * @generated from protobuf field: repeated todo.TodoItem items = 1
     */
    items: TodoItem[];
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: bool success = 3
     */
    success: boolean;
    /**
     * @generated from protobuf field: int32 code = 4
     */
    code: number;
}
/**
 * @generated from protobuf message todo.GetTodosRequest
 */
export interface GetTodosRequest {
    /**
     * @generated from protobuf field: optional string user_id = 1
     */
    userId?: string;
}
/**
 * @generated from protobuf message todo.DeleteTodoRequest
 */
export interface DeleteTodoRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message todo.DeleteTodoResponse
 */
export interface DeleteTodoResponse {
    /**
     * @generated from protobuf field: todo.TodoItem items = 1
     */
    items?: TodoItem;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: bool success = 3
     */
    success: boolean;
    /**
     * @generated from protobuf field: int32 code = 4
     */
    code: number;
}
/**
 * @generated from protobuf enum todo.TodoStatus
 */
export enum TodoStatus {
    /**
     * @generated from protobuf enum value: PENDING = 0;
     */
    PENDING = 0,
    /**
     * @generated from protobuf enum value: COMPLETED = 1;
     */
    COMPLETED = 1
}
// @generated message type with reflection information, may provide speed optimized methods
class TodoItem$Type extends MessageType<TodoItem> {
    constructor() {
        super("todo.TodoItem", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "status", kind: "enum", T: () => ["todo.TodoStatus", TodoStatus] },
            { no: 4, name: "created_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "updated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TodoItem>): TodoItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.message = "";
        message.status = 0;
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<TodoItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TodoItem): TodoItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* todo.TodoStatus status */ 3:
                    message.status = reader.int32();
                    break;
                case /* optional string created_at */ 4:
                    message.createdAt = reader.string();
                    break;
                case /* optional string updated_at */ 5:
                    message.updatedAt = reader.string();
                    break;
                case /* string user_id */ 6:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TodoItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* todo.TodoStatus status = 3; */
        if (message.status !== 0)
            writer.tag(3, WireType.Varint).int32(message.status);
        /* optional string created_at = 4; */
        if (message.createdAt !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.createdAt);
        /* optional string updated_at = 5; */
        if (message.updatedAt !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.updatedAt);
        /* string user_id = 6; */
        if (message.userId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.TodoItem
 */
export const TodoItem = new TodoItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddTodoItemResponse$Type extends MessageType<AddTodoItemResponse> {
    constructor() {
        super("todo.AddTodoItemResponse", [
            { no: 1, name: "item", kind: "message", T: () => TodoItem },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AddTodoItemResponse>): AddTodoItemResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.success = false;
        message.code = 0;
        if (value !== undefined)
            reflectionMergePartial<AddTodoItemResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddTodoItemResponse): AddTodoItemResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* todo.TodoItem item */ 1:
                    message.item = TodoItem.internalBinaryRead(reader, reader.uint32(), options, message.item);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* bool success */ 3:
                    message.success = reader.bool();
                    break;
                case /* int32 code */ 4:
                    message.code = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddTodoItemResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* todo.TodoItem item = 1; */
        if (message.item)
            TodoItem.internalBinaryWrite(message.item, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* bool success = 3; */
        if (message.success !== false)
            writer.tag(3, WireType.Varint).bool(message.success);
        /* int32 code = 4; */
        if (message.code !== 0)
            writer.tag(4, WireType.Varint).int32(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.AddTodoItemResponse
 */
export const AddTodoItemResponse = new AddTodoItemResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTodosResponse$Type extends MessageType<GetTodosResponse> {
    constructor() {
        super("todo.GetTodosResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TodoItem },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GetTodosResponse>): GetTodosResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        message.message = "";
        message.success = false;
        message.code = 0;
        if (value !== undefined)
            reflectionMergePartial<GetTodosResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTodosResponse): GetTodosResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated todo.TodoItem items */ 1:
                    message.items.push(TodoItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* bool success */ 3:
                    message.success = reader.bool();
                    break;
                case /* int32 code */ 4:
                    message.code = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTodosResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated todo.TodoItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            TodoItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* bool success = 3; */
        if (message.success !== false)
            writer.tag(3, WireType.Varint).bool(message.success);
        /* int32 code = 4; */
        if (message.code !== 0)
            writer.tag(4, WireType.Varint).int32(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.GetTodosResponse
 */
export const GetTodosResponse = new GetTodosResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTodosRequest$Type extends MessageType<GetTodosRequest> {
    constructor() {
        super("todo.GetTodosRequest", [
            { no: 1, name: "user_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTodosRequest>): GetTodosRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTodosRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTodosRequest): GetTodosRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string user_id */ 1:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTodosRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string user_id = 1; */
        if (message.userId !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.GetTodosRequest
 */
export const GetTodosRequest = new GetTodosRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTodoRequest$Type extends MessageType<DeleteTodoRequest> {
    constructor() {
        super("todo.DeleteTodoRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTodoRequest>): DeleteTodoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteTodoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTodoRequest): DeleteTodoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTodoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.DeleteTodoRequest
 */
export const DeleteTodoRequest = new DeleteTodoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTodoResponse$Type extends MessageType<DeleteTodoResponse> {
    constructor() {
        super("todo.DeleteTodoResponse", [
            { no: 1, name: "items", kind: "message", T: () => TodoItem },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTodoResponse>): DeleteTodoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.success = false;
        message.code = 0;
        if (value !== undefined)
            reflectionMergePartial<DeleteTodoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTodoResponse): DeleteTodoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* todo.TodoItem items */ 1:
                    message.items = TodoItem.internalBinaryRead(reader, reader.uint32(), options, message.items);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* bool success */ 3:
                    message.success = reader.bool();
                    break;
                case /* int32 code */ 4:
                    message.code = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTodoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* todo.TodoItem items = 1; */
        if (message.items)
            TodoItem.internalBinaryWrite(message.items, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* bool success = 3; */
        if (message.success !== false)
            writer.tag(3, WireType.Varint).bool(message.success);
        /* int32 code = 4; */
        if (message.code !== 0)
            writer.tag(4, WireType.Varint).int32(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message todo.DeleteTodoResponse
 */
export const DeleteTodoResponse = new DeleteTodoResponse$Type();
/**
 * @generated ServiceType for protobuf service todo.TodoService
 */
export const TodoService = new ServiceType("todo.TodoService", [
    { name: "AddTodo", options: {}, I: TodoItem, O: AddTodoItemResponse },
    { name: "GetTodos", options: {}, I: GetTodosRequest, O: GetTodosResponse },
    { name: "DeleteTodo", options: {}, I: DeleteTodoRequest, O: DeleteTodoResponse }
]);
